/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { BodyOauthTokenAuthTokenPostGrantType } from './bodyOauthTokenAuthTokenPostGrantType';
import type { BodyOauthTokenAuthTokenPostClientId } from './bodyOauthTokenAuthTokenPostClientId';
import type { BodyOauthTokenAuthTokenPostClientSecret } from './bodyOauthTokenAuthTokenPostClientSecret';

export interface BodyOauthTokenAuthTokenPost {
  grant_type?: BodyOauthTokenAuthTokenPostGrantType;
  username: string;
  password: string;
  scope?: string;
  client_id?: BodyOauthTokenAuthTokenPostClientId;
  client_secret?: BodyOauthTokenAuthTokenPostClientSecret;
}
