/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { BudgetUpdateCategoryId } from './budgetUpdateCategoryId';
import type { BudgetUpdateAmount } from './budgetUpdateAmount';
import type { BudgetUpdateMonthYear } from './budgetUpdateMonthYear';

export interface BudgetUpdate {
  category_id?: BudgetUpdateCategoryId;
  amount?: BudgetUpdateAmount;
  month_year?: BudgetUpdateMonthYear;
}
