/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface BudgetRead {
  user_id: number;
  category_id: number;
  amount: string;
  month_year: string;
  id: number;
}
