/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type CategoryType = typeof CategoryType[keyof typeof CategoryType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CategoryType = {
  income: 'income',
  expense: 'expense',
} as const;
