/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CategoryType } from './categoryType';

export interface CategoryRead {
  name: string;
  type: CategoryType;
  id: number;
  user_id: number;
}
