/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type CategoryReadType = typeof CategoryReadType[keyof typeof CategoryReadType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CategoryReadType = {
  income: 'income',
  expense: 'expense',
} as const;
