/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface CategoryReportItem {
  category_id: number;
  category_name: string;
  total: number;
}
