/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CategoryReadType } from './categoryReadType';

export interface CategoryRead {
  user_id: number;
  name: string;
  type: CategoryReadType;
  id: number;
}
