/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type CategoryCreateType = typeof CategoryCreateType[keyof typeof CategoryCreateType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CategoryCreateType = {
  income: 'income',
  expense: 'expense',
} as const;
