/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CategoryReportItem } from './categoryReportItem';

export interface CategoryReportResponse {
  start_date: string;
  end_date: string;
  items: CategoryReportItem[];
}
