/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type GetByCategoryReportParams = {
user_id: number;
start_date: string;
end_date: string;
type?: 'income' | 'expense' | null;
};
