/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type GetTrendReportGranularity = typeof GetTrendReportGranularity[keyof typeof GetTrendReportGranularity];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetTrendReportGranularity = {
  daily: 'daily',
  weekly: 'weekly',
  monthly: 'monthly',
} as const;
