/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { GetTrendReportGranularity } from './getTrendReportGranularity';

export type GetTrendReportParams = {
user_id: number;
start_date: string;
end_date: string;
granularity?: GetTrendReportGranularity;
};
