/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { IncomeExpenseItem } from './incomeExpenseItem';

export interface IncomeExpenseResponse {
  items: IncomeExpenseItem[];
}
