/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ListTransactionsParams = {
/**
 * Start date YYYY-MM-DD
 */
start_date?: string;
/**
 * End date YYYY-MM-DD
 */
end_date?: string;
};
