/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ListBudgetsParams = {
user_id: number;
/**
 * Format YYYY-MM
 */
month_year?: string | null;
};
