/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type RecurringPaymentReadFrequency = typeof RecurringPaymentReadFrequency[keyof typeof RecurringPaymentReadFrequency];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RecurringPaymentReadFrequency = {
  daily: 'daily',
  weekly: 'weekly',
  biweekly: 'biweekly',
  monthly: 'monthly',
} as const;
