/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { RecurringPaymentCreateDescription } from './recurringPaymentCreateDescription';
import type { RecurringPaymentCreateFrequency } from './recurringPaymentCreateFrequency';
import type { RecurringPaymentCreateActive } from './recurringPaymentCreateActive';

export interface RecurringPaymentCreate {
  category_id: number;
  amount: number;
  description?: RecurringPaymentCreateDescription;
  frequency: RecurringPaymentCreateFrequency;
  next_due_date: string;
  active?: RecurringPaymentCreateActive;
}
