/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { RecurringPaymentUpdateCategoryId } from './recurringPaymentUpdateCategoryId';
import type { RecurringPaymentUpdateAmount } from './recurringPaymentUpdateAmount';
import type { RecurringPaymentUpdateDescription } from './recurringPaymentUpdateDescription';
import type { RecurringPaymentUpdateFrequency } from './recurringPaymentUpdateFrequency';
import type { RecurringPaymentUpdateNextDueDate } from './recurringPaymentUpdateNextDueDate';
import type { RecurringPaymentUpdateActive } from './recurringPaymentUpdateActive';

export interface RecurringPaymentUpdate {
  category_id?: RecurringPaymentUpdateCategoryId;
  amount?: RecurringPaymentUpdateAmount;
  description?: RecurringPaymentUpdateDescription;
  frequency?: RecurringPaymentUpdateFrequency;
  next_due_date?: RecurringPaymentUpdateNextDueDate;
  active?: RecurringPaymentUpdateActive;
}
