/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { RecurringPaymentReadDescription } from './recurringPaymentReadDescription';
import type { RecurringPaymentReadFrequency } from './recurringPaymentReadFrequency';
import type { RecurringPaymentReadActive } from './recurringPaymentReadActive';

export interface RecurringPaymentRead {
  user_id: number;
  category_id: number;
  amount: number;
  description?: RecurringPaymentReadDescription;
  frequency: RecurringPaymentReadFrequency;
  next_due_date: string;
  active?: RecurringPaymentReadActive;
  id: number;
}
