/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type TransactionCreateType = typeof TransactionCreateType[keyof typeof TransactionCreateType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TransactionCreateType = {
  manual: 'manual',
  auto: 'auto',
} as const;
