/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type TransactionReadType = typeof TransactionReadType[keyof typeof TransactionReadType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TransactionReadType = {
  manual: 'manual',
  auto: 'auto',
} as const;
