/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { TransactionReadDescription } from './transactionReadDescription';
import type { TransactionReadType } from './transactionReadType';
import type { TransactionReadStatus } from './transactionReadStatus';
import type { TransactionReadRecurringId } from './transactionReadRecurringId';
import type { TransactionReadFailureReason } from './transactionReadFailureReason';

export interface TransactionRead {
  user_id: number;
  category_id: number;
  amount: number;
  date: string;
  description?: TransactionReadDescription;
  type?: TransactionReadType;
  status?: TransactionReadStatus;
  recurring_id?: TransactionReadRecurringId;
  failure_reason?: TransactionReadFailureReason;
  id: number;
}
