/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { TransactionUpdateCategoryId } from './transactionUpdateCategoryId';
import type { TransactionUpdateAmount } from './transactionUpdateAmount';
import type { TransactionUpdateDescription } from './transactionUpdateDescription';
import type { TransactionUpdateType } from './transactionUpdateType';
import type { TransactionUpdateStatus } from './transactionUpdateStatus';
import type { TransactionUpdateRecurringId } from './transactionUpdateRecurringId';
import type { TransactionUpdateFailureReason } from './transactionUpdateFailureReason';

export interface TransactionUpdate {
  category_id?: TransactionUpdateCategoryId;
  amount?: TransactionUpdateAmount;
  date?: null;
  description?: TransactionUpdateDescription;
  type?: TransactionUpdateType;
  status?: TransactionUpdateStatus;
  recurring_id?: TransactionUpdateRecurringId;
  failure_reason?: TransactionUpdateFailureReason;
}
