/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type TransactionCreateStatus = typeof TransactionCreateStatus[keyof typeof TransactionCreateStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TransactionCreateStatus = {
  pending: 'pending',
  completed: 'completed',
  failed: 'failed',
} as const;
