/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type TransactionReadStatus = typeof TransactionReadStatus[keyof typeof TransactionReadStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TransactionReadStatus = {
  pending: 'pending',
  completed: 'completed',
  failed: 'failed',
} as const;
