/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type TrendReportResponseGranularity = typeof TrendReportResponseGranularity[keyof typeof TrendReportResponseGranularity];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TrendReportResponseGranularity = {
  daily: 'daily',
  weekly: 'weekly',
  monthly: 'monthly',
} as const;
