/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { UserUpdateFirstName } from './userUpdateFirstName';
import type { UserUpdateLastName } from './userUpdateLastName';
import type { UserUpdateTelephone } from './userUpdateTelephone';
import type { UserUpdatePassword } from './userUpdatePassword';

export interface UserUpdate {
  first_name?: UserUpdateFirstName;
  last_name?: UserUpdateLastName;
  telephone?: UserUpdateTelephone;
  password?: UserUpdatePassword;
}
