/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { UserCreateTelephone } from './userCreateTelephone';

export interface UserCreate {
  first_name: string;
  last_name: string;
  email: string;
  telephone?: UserCreateTelephone;
  password: string;
}
