/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { UserReadTelephone } from './userReadTelephone';
import type { UserReadModifiedOn } from './userReadModifiedOn';

export interface UserRead {
  first_name: string;
  last_name: string;
  email: string;
  telephone?: UserReadTelephone;
  id: number;
  email_verified: boolean;
  created_on: string;
  modified_on: UserReadModifiedOn;
}
